# Copyright 2015 0xc0170
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import os
from os.path import normcase
import logging
import sys

from project_generator.generate import Generator

def run(args):

    # Export if we know how, otherwise return
    if os.path.exists(args.file):
        generator = Generator(args.file)
        # iterate over the projects generated by the args.file yaml file
        root = os.getcwd()
        for project in generator.generate(args.project, ''):
            # build each project for the given tool
            if project is None or project.build(args.dev, normcase(args.exe)) is None:
                sys.exit(1)
            os.chdir(root)
    else:
        # not project known by pgen
        logging.warning("%s not found." % args.file)

def setup(subparser):
    subparser.add_argument(
        "-f", "--file", help="YAML projects file (.projects.yaml by default)", default='.projects.yaml')
    subparser.add_argument(
        "-p", "--project", help="Project to be built defined in .projects.yaml", default='')
    subparser.add_argument(
        "-d", "--dev", help="Create project files for specified development tool", type=str.lower)
    subparser.add_argument(
        "-e", "--exe", help="Exec for specified development tool", default = '')

