# Copyright 2014-2015 0xc0170
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import sys
import os
import logging

from project_generator.generate import Generator

def run(args):
    if os.path.exists(args.file):
        generator = Generator(args.file)
        # iterate over the projects generated by the args.file yaml file
        root = os.getcwd()
        for project in generator.generate(args.project, args.ignore):
            #generate a project file for each one for the specified tool
            if project is None or project.generate(args.copy, args.dev, args.target, args.settings) is None:
                if project is not None:
                    logging.critical("Failed to generate project files for %s.",project.name)
                sys.exit(1)
            logging.info("%s generated successfully for %s."%(project.name,project.tool))
            os.chdir(root)
    else:
        # not project known by pgen
        logging.warning("%s not found." % args.file)

def setup(subparser):
    subparser.add_argument(
        "-f", "--file", help="YAML projects file (.projects.yaml by default)", default='.projects.yaml')
    subparser.add_argument(
        "-p", "--project", help="Project to be generated defined in .projects.yaml", default='')
    subparser.add_argument(
        "-d", "--dev", help="Create project files for specified development tool", type=str.lower)
    subparser.add_argument(
        "-i", "--ignore", nargs='+', help="Directories to be ignored", type=str, default=['execbuild', 'projectfiles'])
    subparser.add_argument("-t", "--target", help="Target specific yaml configuration file")
    subparser.add_argument("-s", "--settings", help="Platform settings for a development tool")
    subparser.add_argument("-c", "--copy", action="store_true", help="Copy all files to the exported directory")
