# Copyright 2014-2015 0xc0170
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import sys
from ..main import *
from ..generate import Generator
import logging

def run(args):
    if os.path.exists(args.file):
        generator = Generator(args.file)
        # iterate over the projects generated by the args.file yaml file
        for project in generator.generate(args.project, args.ignore):
            #generate a project file for each one for the specified tool
            if project is None or project.generate(args.copy, args.tool, args.target, args.settings) is None:
                logging.critical("Failed to generate project files for %s.",project.name)
                sys.exit(1)
            logging.info("%s generated successfully for %s."%(project.name,project.tool))
    else:
        # not project known by pgen
        logging.warning("%s not found." % args.file)

def setup(subparser):
    subparser.add_argument(
        "-f", "--file", help="YAML projects file (.projects.yaml by default)", default='.projects.yaml')
    subparser.add_argument(
        "-p", "--project", help="Project to be generated", default='')
    subparser.add_argument(
        "-t", "--tool", help="Create project files for provided tool", type = str.lower)
    subparser.add_argument(
        "-i", "--ignore", nargs='+', help="Directories to be ignored", type = str, default= ['generated_projects'])
    subparser.add_argument("-tar", "--target", help="Target configuration file")
    subparser.add_argument("-settings", "--settings", help="Tool configuration file")
    subparser.add_argument(
        "-defdir", "--defdirectory",
        help="Path to the definitions, otherwise default (~/.pg/definitions) is used")
    subparser.add_argument(
        "-c", "--copy", action="store_true", help="Copy all files to the exported directory")
